// <auto-generated />
using System;
using CurlingRinkManagement.Planner.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CurlingRinkManagement.Planner.Business.Migrations
{
    [DbContext(typeof(PlannerDataContext))]
    [Migration("20250505073749_AddedClubId")]
    partial class AddedClubId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CurlingRinkManagement.Planner.Data.DatabaseModels.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("CustomerRequestId")
                        .IsUnique();

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("CurlingRinkManagement.Planner.Data.DatabaseModels.ActivityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecommendedMinutesBlockedAfter")
                        .HasColumnType("integer");

                    b.Property<int>("RecommendedMinutesBlockedBefore")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("CurlingRinkManagement.Planner.Data.DatabaseModels.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClubId", "Email")
                        .IsUnique();

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("CurlingRinkManagement.Planner.Data.DatabaseModels.CustomerRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AmountOfPeople")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<float>("CustomPrice")
                        .HasColumnType("real");

                    b.Property<string>("CustomPriceReason")
                        .HasColumnType("text");

                    b.Property<int>("CustomerRequestState")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("CustomerRequests");
                });

            modelBuilder.Entity("CurlingRinkManagement.Planner.Data.DatabaseModels.Sheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Sheets");
                });

            modelBuilder.Entity("CurlingRinkManagement.Planner.Data.DatabaseModels.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("ParentId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("CurlingRinkManagement.Planner.Data.DatabaseModels.Activity", b =>
                {
                    b.HasOne("CurlingRinkManagement.Planner.Data.DatabaseModels.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CurlingRinkManagement.Planner.Data.DatabaseModels.CustomerRequest", "CustomerRequest")
                        .WithOne("Activity")
                        .HasForeignKey("CurlingRinkManagement.Planner.Data.DatabaseModels.Activity", "CustomerRequestId");

                    b.OwnsMany("CurlingRinkManagement.Planner.Data.DatabaseModels.DateTimeRange", "PlannedDates", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ClubId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("MinutesBlockedAfter")
                                .HasColumnType("integer");

                            b1.Property<int>("MinutesBlockedBefore")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ActivityId", "Id");

                            b1.ToTable("DateTimeRanges");

                            b1.WithOwner("Activity")
                                .HasForeignKey("ActivityId");

                            b1.Navigation("Activity");
                        });

                    b.OwnsMany("CurlingRinkManagement.Planner.Data.DatabaseModels.SheetActivity", "Sheets", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ClubId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("SheetId")
                                .HasColumnType("uuid");

                            b1.HasKey("ActivityId", "Id");

                            b1.HasIndex("SheetId");

                            b1.ToTable("SheetActivity");

                            b1.WithOwner("Activity")
                                .HasForeignKey("ActivityId");

                            b1.HasOne("CurlingRinkManagement.Planner.Data.DatabaseModels.Sheet", "Sheet")
                                .WithMany()
                                .HasForeignKey("SheetId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("Activity");

                            b1.Navigation("Sheet");
                        });

                    b.Navigation("ActivityType");

                    b.Navigation("CustomerRequest");

                    b.Navigation("PlannedDates");

                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("CurlingRinkManagement.Planner.Data.DatabaseModels.CustomerRequest", b =>
                {
                    b.HasOne("CurlingRinkManagement.Planner.Data.DatabaseModels.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("CurlingRinkManagement.Planner.Data.DatabaseModels.Tag", b =>
                {
                    b.HasOne("CurlingRinkManagement.Planner.Data.DatabaseModels.Contact", null)
                        .WithMany("Tags")
                        .HasForeignKey("ContactId");

                    b.HasOne("CurlingRinkManagement.Planner.Data.DatabaseModels.Tag", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CurlingRinkManagement.Planner.Data.DatabaseModels.Contact", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("CurlingRinkManagement.Planner.Data.DatabaseModels.CustomerRequest", b =>
                {
                    b.Navigation("Activity");
                });
#pragma warning restore 612, 618
        }
    }
}
